name: Checkmarx One Scan

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

permissions:
  security-events: write
  contents: read

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkmarx AST Scan
        uses: Checkmarx/ast-github-action@2.0.28  # Updated to latest version
        with:
          base_uri: https://ast.checkmarx.net
          cx_tenant: sonype-01
          cx_client_id: Test-Github-Suramya
          cx_client_secret: kAmCLxJ69sKmdw01fibmSoxmAow9giZC
          project_name: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          additional_params: --report-format sarif --output-path .

      - name: Filter and Upload SARIF
        if: success()
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          
          # Filter SARIF
          jq '
          .runs[].results |= map(
            select(
              (.ruleId | startswith("Cx") | not) and
              ((.tags.Usage // []) | contains(["Used"]) or contains(["Potentially Used"]) or length == 0)
            )
          )
          ' cx_result.sarif > filtered_cx_result.sarif
          
          # Upload filtered SARIF
          gh security-events upload-sarif filtered_cx_result.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail on High Severity Issues
        if: success()
        run: |
          HIGH_SEVERITY_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' filtered_cx_result.sarif)
          if [ $HIGH_SEVERITY_COUNT -gt 0 ]; then
            echo "Found $HIGH_SEVERITY_COUNT high severity issues. Failing the build."
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: rm -f cx_result.sarif filtered_cx_result.sarif
